### ISSUE TITLE
Theme tables

### ISSUE THREAD

**Issue by iris-i** [CivicActions/web-design-standards-drupal#21]
Confirm that tables are themed. Test with the HTML output from: https://playbook.cio.gov/designstandards/tables/

This issue is mirrored in the 18F repo here: https://github.com/18F/web-design-standards-drupal/issues/34. Assign yourself to the 18F ticket once you start working on this, and move that ticket along the 18F waffle board as you work on this.

**Comment by hrod** [comment]
<img width="1050" alt="screen shot 2016-04-08 at 12 36 53 pm" src="https://cloud.githubusercontent.com/assets/4369591/14395482/e413fc4a-fd86-11e5-8999-7edc27ef8f2d.png">
<img width="1009" alt="screen shot 2016-04-08 at 12 40 54 pm" src="https://cloud.githubusercontent.com/assets/4369591/14395544/2b225bd6-fd87-11e5-9348-60cf5b1f8cbe.png">

confirmed!

**Comment by hrod** [comment]
So a spinoff ticket that could be created would be to allow users to select styles (i.e. borderless table) so they don't have to apply the class of usa-borderless-table but can instead go into their ckeditor and go "borderless" for table. Not necessarily vital for MVP, but a nice to have!
